# SPDX-FileCopyrightText: 2022 René de Hesselle <dehesselle@web.de>
#
# SPDX-License-Identifier: GPL-2.0-or-later

variables:
  GIT_DEPTH: 1
  GIT_SUBMODULE_STRATEGY: recursive
  WRK_DIR: /Users/Shared/work
  CCACHE_DIR: /Users/Shared/work/ccache

stages:
  - prepare
  - build
  - release

#----------------------------------------------------------------- configuration

.config:arm64:
  variables:
    SDKROOT: /opt/sdks/MacOSX11.3.sdk
  tags:
    - bigsurarm

.config:x86_64:
  variables:
    SDKROOT: /opt/sdks/MacOSX10.11.4.sdk
  tags:
    - bigsur

#----------------------------------------------------------------------- prepare

include:
  - remote: https://raw.githubusercontent.com/dehesselle/sdkchecksum/master/.gitlab-ci/verify_sdk-template.yml

verify_sdk:x86_64:
  stage: prepare
  extends:
    - .config:x86_64
    - .verify_sdk

verify_sdk:arm64:
  stage: prepare
  extends:
    - .config:arm64
    - .verify_sdk

#------------------------------------------------------------------------- build

.build:
  stage: build
  script:
    - usr/bin/bootstrap
    - |
      source etc/jhb.conf.sh
      find "$SRC_DIR" -mindepth 1 -maxdepth 1 -type d ! -name bash_d ! -name "jhb*" -exec rm -rf {} \;
      rm -rf "$VAR_DIR"/build/*
      rm -rf "$VAR_DIR"/cache/pip/*
      rm -rf "$VAR_DIR"/cache/pycache/*
      rm -rf "${TMP_DIR:?}"/*
    - usr/bin/archive create_tar
  after_script:
    # For persistent runners: cleanup afterwards.
    - source etc/jhb.conf.sh
    - rm -rf $VER_DIR
  artifacts:
    paths:
      - jhb-*.tar.xz

build:arm64:
  needs:
    - verify_sdk:arm64
  extends:
    - .config:arm64
    - .build

build:x86_64:
  needs:
    - verify_sdk:x86_64
  extends:
    - .config:x86_64
    - .build

#----------------------------------------------------------------------- release

release:
  stage: release
  only:
    - tags
  image: python:3-alpine
  script:
    - pip3 install gitlab-release==5.6
    - gitlab-release jhb-*.tar.xz
