# SPDX-FileCopyrightText: 2021 René de Hesselle <dehesselle@web.de>
#
# SPDX-License-Identifier: GPL-2.0-or-later

name: Build
on:
  push:   # do not run for tags
    branches:
      - '*'
  workflow_call:
jobs:

################################################################################

  jhb:
    runs-on: macos-14
    env:
      WRK_DIR: /Users/Shared/work
      CCACHE_DIR: /Users/Shared/work/ccache
    steps:

      #----------------------------------------------------------------- prepare

      - name: Checkout jhb repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Create timestamp
        id: timestamp
        uses: josStorer/get-current-time@v2
        with:
          format: "YYYY-MM-DD-HH-mm-ss"

      # Create a new cache, building ontop the most recent old one.
      - name: Set up cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-jhb-${{ steps.timestamp.outputs.formattedTime }}
          restore-keys: ccache-jhb-

      #------------------------------------------------------------------- build

      - name: Bootstrap JHBuild
        env:
          FORCE_BUILD_FROM_SOURCE: true
        run: usr/bin/bootstrap

      - name: Create archive
        run: |
          usr/bin/archive remove_nonessentials
          usr/bin/archive create_tar

      #---------------------------------------------------------- upload archive

      - name: upload archive
        uses: actions/upload-artifact@v4
        with:
          name: jhb
          path: jhb*.tar.xz
