# SPDX-FileCopyrightText: 2021 René de Hesselle <dehesselle@web.de>
#
# SPDX-License-Identifier: GPL-2.0-or-later

name: release
on:
  push:   # only run for tags
    tags:
      - 'v*'
jobs:

# This workflow...
#
#   ... deserves some documentation here :D
#
#

################################################################################

  check_requirements:
    runs-on: macos-10.15
    steps:

      - name: checkout jhb repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: fail on missing version tag
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/github-script@v3
        with:
          script: core.setFailed("version tag not found")

      - name: get jhb version
        id: jhb
        env:
          SYS_IGNORE_USR_LOCAL: true
        run: |
          source etc/bootstrap.conf.d/version.sh
          echo "::set-output name=version::$VERSION"

      - name: get version tag
        id: tag
        run: echo "::set-output name=version::${GITHUB_REF##*v}"

      # Once we have established that the jhb version (version.sh)
      # matches the git tag we can safely rely on the tag from here on.
      - name: fail on version mismatch
        if: ${{ !endsWith(github.ref, steps.jhb.outputs.version) }}
        uses: actions/github-script@v3
        with:
          script: core.setFailed("version tag mismatch")

      - name: fail on missing secret SDK_DOWNLOAD_URL
        if: env.SDK_DOWNLOAD_URL == null
        env:
          SDK_DOWNLOAD_URL: ${{ secrets.SDK_DOWNLOAD_URL }}
        uses: actions/github-script@v3
        with:
          script: core.setFailed("SDK_DOWNLOAD_URL secret not found")

################################################################################

  build:
    runs-on: macos-10.15
    needs: check_requirements
    env:
      WRK_DIR: /Users/Shared/work
      CCACHE_DIR: /Users/Shared/work/ccache
    steps:

      #------------------------------------------------- prepare the environemnt

      - name: checkout jhb repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: create cache id
        id: cache_id
        uses: nanzm/get-time-action@v1.1
        with:
          format: "YYYY-MM-DD-HH-mm-ss"

      # Create a new cache, building ontop the most recent old one.
      - name: setup cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-jhb-${{ steps.cache_id.outputs.time }}
          restore-keys: ccache-jhb-

      # GitHub does not provide 10.11 SDK on their runners and no image older
      # than Catalina. See here for what you can expect in their Catalina image:
      # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
      #
      # Official downloads from Apple are not accessible without a developer
      # account and I don't trust 3rd party sources (e.g. "phracker"). So I'm
      # using my own (non-public) source, but I'm providing the means to verify
      # what I'm doing, see here:
      # https://github.com/dehesselle/sdkchecksum
      #
      # In order to use your custom SDK_DOWNLOAD_URL, create a repository secret
      # of said name and proivide a link to a .tar.xz file.
      # At the moment, only 10.11.4 SDK is supported (hardcoded below).
      - name: install macOS SDK
        if: env.SDK_DOWNLOAD_URL != null
        env:
          SDK_DOWNLOAD_URL: ${{ secrets.SDK_DOWNLOAD_URL }}
        run: |
          mkdir -p $WRK_DIR
          curl -L ${{ secrets.SDK_DOWNLOAD_URL }} | tar -C $WRK_DIR -xJp
          echo "SDKROOT=$WRK_DIR/$(basename ${SDK_DOWNLOAD_URL%%.tar.xz*})" >> $GITHUB_ENV

      # Checkout repository to verify SDK...
      - name: checkout sdkchecksum repository
        if: env.SDK_DOWNLOAD_URL != null
        env:
          SDK_DOWNLOAD_URL: ${{ secrets.SDK_DOWNLOAD_URL }}
        uses: actions/checkout@v2
        with:
          repository: dehesselle/sdkchecksum
          path: sdkchecksum
          clean: false

      # ...and use it to verify
      - name: verify SDK
        if: env.SDK_DOWNLOAD_URL != null
        env:
          SDK_DOWNLOAD_URL: ${{ secrets.SDK_DOWNLOAD_URL }}
        run: |
          shasum -a 256 sdkchecksum/MacOSX10.11.4.sdk.sha256
          cd $WRK_DIR
          if shasum -s -c $GITHUB_WORKSPACE/sdkchecksum/MacOSX10.11.4.sdk.sha256; then
            echo "ok - SDK verified"
            exit 0
          else
            echo "error - SDK verification failed"
            exit 1
          fi

      # GitHub does not provide a clean macOS installation. We need to move the
      # pre-installed components out of the way so we don't pick them up by
      # accident.
      - name: disable /usr/local
        run: |
          cd /usr/local
          for dir in include lib share; do sudo mv $dir $dir.disabled; done

      #------------------------------------------------------------------- build

      - name: bootstrap JHBuild
        run: usr/bin/bootstrap

      - name: create archive
        id: jhb
        run: |
          source etc/bootstrap.conf.d/version.sh
          tar -C $WRK_DIR -cp jhb-$VERSION | XZ_OPT=-T0 $WRK_DIR/jhb-$VERSION/bin/xz > $GITHUB_WORKSPACE/jhb_v$VERSION.tar.xz
          shasum -a 256 $GITHUB_WORKSPACE/jhb_v$VERSION.tar.xz > $GITHUB_WORKSPACE/jhb_v$VERSION.tar.xz.sha256
          cat $GITHUB_WORKSPACE/jhb_v$VERSION.tar.xz.sha256
          echo "::set-output name=version::$VERSION"

      #-------------------------------------------------------- upload artifacts

      # Restore /usr/local, GitHub actions depend on these.
      - name: restore /usr/local
        run: for dir in /usr/local/*.disabled; do sudo mv $dir ${dir/.disabled/}; done

      - name: upload archive
        uses: actions/upload-artifact@v2
        with:
          name: jhb_archive
          path: jhb_v${{ steps.jhb.outputs.version }}.tar.xz

      - name: upload archive checksum
        uses: actions/upload-artifact@v2
        with:
          name: jhb_archive.sha256
          path: jhb_v${{ steps.jhb.outputs.version }}.tar.xz.sha256


################################################################################

  create_release:
    runs-on: macos-10.15
    needs: build
    env:
      WRK_DIR: /Users/Shared/work
    steps:

    #--------------------------------------------------- prepare the environment

      - name: checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: jhb_archive

      - name: download artifact checksum
        uses: actions/download-artifact@v2
        with:
          name: jhb_archive.sha256

      - name: get jhb version
        id: jhb
        run: |
          echo "::set-output name=tag::${GITHUB_REF##*/}"
          echo "::set-output name=version::${GITHUB_REF##*v}"

    #------------------------------------------------------------ create release

      - name: create release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: jhb ${{ github.ref }}
          draft: true
          prerelease: false

      - name: upload archive to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: jhb_${{ steps.jhb.outputs.tag }}.tar.xz
          asset_name: jhb_${{ steps.jhb.outputs.tag }}.tar.xz
          asset_content_type: application/octet-stream

      - name: upload toolset checksum to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: jhb_${{ steps.jhb.outputs.tag }}.tar.xz.sha256
          asset_name: jhb_${{ steps.jhb.outputs.tag }}.tar.xz.sha256
          asset_content_type: text/plain
