# SPDX-FileCopyrightText: 2021 René de Hesselle <dehesselle@web.de>
#
# SPDX-License-Identifier: GPL-2.0-or-later

name: Release
on:
  push:   # only run for version tags
    tags:
      - 'v*'
jobs:

################################################################################

  build:
    uses: ./.github/workflows/build.yml

################################################################################

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Download jhb archive
        uses: actions/download-artifact@v4
        with:
          name: jhb

      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: jhb*.tar.xz
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
